import React, { Component } from 'react'

export default class example4 extends Component {
    render() {
        return (
            <div className="content">
                <h3>Türk Siyasi Yaşamı ve Sorunları</h3>
                <h5>İktisadi, Kültürel ve Siyasi Dönüşüm</h5>
                <p>1980 darbesiyle siyasal şiddetin son bulması, topluma güvenlik anlamında nefes aldırmıştır.  Evren, 1961 anayasasının sağladığı özgürlükleri siyasal çekişmelerin sebebi saymış, yürütmeyi güçlendirme anlayışını benimsemiştir. 1982 anayasası, bu anlayış çerçevesinde oluşturulmuştur ve çokça eleştirilmesine rağmen sağladığı avantajlardan ötürü değiştirilememiştir. 1982 Anayasası’yla Klasik Parlamentarizmden uzaklaşılmış, Yarı Başkanlık sistemi zorlanılmıştır. </p>
                <p>12 Eylül’le beraber siyasal ve sendikal aktörlerin etkisizleştirilmesi iktisadi dönüşüm projesinin ayağıdır, darbe ve Özal yönetimleri işçilerin kazanımlarını budamak adına kararlı politikalar izlemiştir. 1980 sonrası Atatürkçülüğün sağ yorumu benimsenmiş, kimliksel çatışmaya dayalı siyasal ayrışmalara sebep olan kültürel dönüşüm yaşanmıştır. </p>            
                <p>Darbe sonrası siyasetten bıkmış toplum ANAP’ın zenginleşme vaatli siyasetinin büyüsüne kapılmıştır. Özal, eski liderleri halkın gözünde şiddetle özdeşleştirerek kriminalize etmiştir. Özal, muhafazakarların orta sınıflaşmasına yardımcı olmuş, bu kesimin mağduriyet hissiyatını kullanmıştır. İki Ulus projesini hayata geçirmiş, yandaş görülenler ve görülmeyenler arasında ayrımcılık temelli strateji sürdürmüştür. Bu dönemde popüler kültür eksenli, entelektüelliğin anlamsızlaştığı, zenginleşme amaçlı bir toplum inşa edilmiştir. Özal küreselleşmeden çekinmeyen, dış politikada pragmatik politikalar sürdürmüştür. </p>

                <h5>Müzmin Toplumsal Çatışma</h5>
                <p>1990’lı yıllarda İslam adına şiddet tırmanışa geçmiş, Mumcu ve Kışlalı gibi birçok aydın bu şiddetin kurbanı olmuştur. Bir diğer çatışmaysa, Kürt Sorununun çözülememiş oluşuydu. Kürt kimliğinin denetlenmesi devam etmekte, Kürtlerin farkındalıklarıysa artmaktaydı. 90’lı yıllarda sorunun çözümüne dair adımlar atılmak istense de bu adımlar milliyetçiliğin ağına takılmıştır. Çiller’in başta savunduğu yöntem siyasetin tek kalıcı çözüm odağı olmasıyken kısa süre sonunda bu anlayış yerini terörle mücadelede sert söyleme bırakmıştır. Siyasi ortamın gerginliğiyle, PKK teröründeki tırmanış birleşince sağduyunun sesi duyulamaz olmuştur. Ülke içerisindeki diğer çatışma unsuruysa Alevilere uygulanan şiddetti. Madımak Oteli’yle tekrar alevlenen şiddet Sivas katliamı ve Gazi olaylarıyla devam etmiştir. Bu olaylar Alevilerin kimliklerini daha çok benimsemelerine ve korunmalarına sebep olmuştur.</p>
                <img src={"https://i.sozcu.com.tr/wp-content/uploads/2020/07/02/iecrop/detay-kopya_16_9_1593664423.jpg"}></img>
                <p>İktisadi krizi kontrol etmede başarılı olamayan DYP-SHP Koalisyonu ilerleyen yıllarda Siyasal İslam’ın seçim zaferini hazırlamıştır. Küresel kapitalizmin sendikasızlaştırma, taşeronlaştırma gibi yönelimleri Çiller Hükümeti’ni etkileyerek, işçilerin haklarını ellerinden alma bir devlet politikası haline getirilmiştir.</p>

                <h5>Siyasal İslam’ın Kademeli Yükselişi </h5>
                <p>80’li yılların sonlarından itibaren artan radikal İslamcılık RP’nin yükselişine katkıda bulunmuştur. RP’nin en büyük başarısı orta sınıfın beklentilerini karşılamaktan çok yoksul sınıfa hitap edebilmesi ve onlara ümit aşılayabilmesidir. Merkez sağın liderleri Çiller ve Yılmaz Batıcı-Milliyetçi söylemleri benimserken kentlerde unutulan yoksul kesimin sesi RP tarafından duyulacaktı. Parti içerisinde iki çatışan gruba bölünmüştü; RP Genel Merkezi ve Erdoğan’ın da içinde bulunduğu yeni nesil Millî Görüş kuşağı arasında gerilim mevcuttu. Erbakan, 1996 yılında cumhuriyetin 73 yıllık tarihindeki ilk İslamcı Başbakan olmuştur. Refahyol Hükümeti; mafya-devlet-polis ilişkisinin açığa çıktığı, Susurluk gibi büyük bir skandalla çalkalanan dönemde görevdeydi. RP, laikliğe karşı rövanşist bir tutum takındığı yönünde eleştirilmiştir. Bu sebeple, 28 Şubat’ta MGK, anti-laik hareketlere karşı çıktığı iddiasıyla Erbakan’ın istifasını istemiştir. 28 Şubat süreci aynı zamanda kentli-laik kesimin toplumsal ayrıcalıklarını kaybetmelerine ve Siyasal İslam’a karşı verdikleri bir tepkiydi. Buna ek olarak TÜSİAD ve TOBB gibi örgütlenmelerin MÜSİAD’ın yükselişinden duyduğu rahatsızlık bu süreçte önemli bir etkendir. </p>
                <p>1999 yılında Öcalan’ın yakalanması milliyetçi duyguları kabartmış, medyanın milliyetçi söylemi desteklemesiyle bu durum MHP’nin kısa baharına sebep olmuştur. Milliyetçi söylemle toplumun dikkatini kolayca çekebilen siyasiler sıklıkla bu yola başvurmuş, sonuçta toplumsal çözülme sürecine katkıda bulunmuşlardır. </p>
                
                <h5>Erdoğan ve İmaj Siyaseti</h5>
                <p>2001’deki krizin ardından ekonomi normalleştirilmeye çalışılmıştır. Bu dönemde muhafazakâr iş çevreleri zenginleşmiş, istikrara verdikleri önem neticesinde RP’den uzaklaşarak AKP’yi desteklemişlerdir. AKP; 2002 yılında genel seçimleri kazanmış, Millî Görüş anlayışından uzaklaşarak Muhafazakâr-Demokrat bir parti izlenimi vermiştir. Bu dönemde AB ile entegrasyona öncelik verilmiştir. Merkel ve Sarkozy gibi liderlerin Türkiye’yi AB içerisinde görmek istememesi süreci yavaşlatmıştır. </p>
                <p>2012’de Barış Süreci’yle Kürt Sorununun demokratik yollarla çözülmesi için çalışılmıştır. Bu sorundaki demokratikleşme adımı her alanda görülmemekte, AKP iktidarı otoriterlikle suçlanmaktaydı. Ergenekon ve Balyoz davalarıyla, birçok alakasız kişinin tutuklanması hukukun siyasallaştığının bir kanıtıydı. AKP’nin otoriterliğine karşı en büyük eylem ise Gezi Parkı eylemi olmuştur. </p>
            </div>
        )
    }
}
