import React, { Component } from 'react'
import Referencecard2 from '../components/Referencecard2'

export default class example2 extends Component {
    render() {
        return (
            <div className="row">
                <div className="content">
                    <h3>İslamda Eşcinsellik ve Çeçenistan'daki Gay Kampları</h3>
                    <p>Bu çalışmada İslam’da Eşcinsellik konusu tartışıldıktan sonra Çeçenistan’daki gey tecrit kampları olayı incelenmiştir. Eşcinsellik konusunun tek tanrılı dinlerde ve özellikle İslam’da nasıl tanımlandığı, cinsel yönelim olarak mı davranış olarak mı ele alındığı, eşcinsel ve dindar bireyin konumu araştırılmıştır. Çeçenistan’da eşcinsellere yönelik şiddetin sebepleri irdelenmiş, toplumsal cinsiyet ve din temel alınarak açıklamalarda bulunulmuştur. </p>
                    <h5>İslam’da Eşcinsellik</h5>
                    <p>İslam’ın eşcinselliğe bakışını incelemeden önce eşcinselliğin tanımının yapılması gerekmektedir. Amerikan Psikologlar Derneği (APA) eşcinselliği, “kişinin kendi cinsinden bir bireye karşı, sürekli (enduring), duygusal (emotional), romantik, cinsel ya da sevgiye dayalı (affectional) ilgi duyduğu bir cinsel yönelim” olarak tanımlamış (Sherblom ve Bahr, 2008) ve “araştırmaların çoğunluğunun, eşcinsel duyguların, iradi olarak seçilen bir şey değil, bireyin psişesinin bir parçası olduğunu gösterdiği” sonucuna varmıştır (Paul, Weinrich, Gonsiorek ve Hotvedt, 1982:24). </p>
                    <p>Eşcinsellik her ne kadar bireyin psişesinin bir parçası olarak tanımlansa da tek tanrılı dinlerde eşcinselliğe olumsuz bir bakış olduğunu söyleyebiliriz. Öncelikle tek tanrılı dinlerde eşcinselliğin kimlik olarak mı davranış olarak mı ele alındığını sorgulamalıyız. Eşcinsellik Kuran’da bir cinsel yönelim olarak değil livata yani erkekler arası cinsel ilişki olarak geçmektedir. Klasik İslam Hukuku çalışmalarında homoseksüellik kavramını açıkça ele alan fetvaların bulunmaması şaşırtıcı değildir. Bunun nedeni Homoseksüellik teriminin, 19. Yüzyılda tıp literatüründe ortaya çıkmış ve somut bir homoseksüellik kimliğinin ise ancak 20. Yüzyılda konsolide edilmiş ve yaygınlaştırılmış olmasıdır. (Zollner, Barbara 2011). Benzer biçimde, Kitab-ı Mukaddes; kimlik ya da yönelim olarak eşcinselliğe mi, yoksa davranış olarak eşcinselliğe mi karşıdır sorusunu yönelten Ellens (1997), yönelim ya da kimlik olarak eşcinsellik (homosexuality as an orientation) ile eşcinsel davranış (homosexuality as a behavior) arasında bir ayrım yapılmasının önemli olduğunu vurgulamış ve Kitab-ı Mukaddesteki pasajlarda açık bir şekilde eşcinsel yönelime değil eşcinsel davranışa vurgu olduğunu savunmuştur. (Kıraç, 2014)</p>
                    <p>Tek tanrılı dinlerde eşcinsellik meselesi Lût kavmi hikayesinde yoğunlaşmaktadır. Hz. Lût, Sodom ve Gomore’de peygamber olarak görevlendirilmiştir; Lût kavmi sözü ile kastettiğimiz aslında Sodom sakinleridir. Lût kavmi eşcinsel ilişkiye girdikleri yani Kuran’da ifade edildiği şekliyle livata yaptıkları için cezalandırılmıştır. Ankebût suresi 28. Ayet’te: “Lût’a gelince o kavmine demişti ki: Siz kesinlikle daha önce hiçbir milletten hiç kimsenin yapmadığı bir hayâsızlığı yapıyorsunuz.” buyrulmuştur. Buradan anlayacağımız üzere bu kavimde -daha önce görülmemiş olduğunun altı çizilerek- eşcinsel ilişkinin çok yaygınlaştığı ifade edilmiştir. Bundan dolayı bu kavim cezaya çarptırılmıştır. Hristiyanlıkta da bu kavimden Yaradılış 19:23-26’da şu şekilde bahsedilmektedir: ‘’İçerdeki iki adam Lût’a, “Senin burada başka kimin var?” diye sordular, “Oğullarını, kızlarını, damatlarını, kentte sana ait kim varsa hepsini dışarı çıkar. Çünkü burayı yok edeceğiz. Rab bu halk hakkında birçok kötü suçlama duydu, kenti yok etmek için bizi gönderdi.” </p>
                    <p>Lût kavminin cezalandırılmasındaki sebep cinsel davranışlarıdır. Bu durumda hem kimlik olarak eşcinsellik durumu hem de livatanın cezası yoruma bırakılmış olup, İslam’ın farklı mezheplerinde farklı yorumlanmış ve farklı cezalar öngörülmüştür. Örneğin; Zahiri mezhebinden İbn Hazm, livata fiilini işleyene verilen ölüm cezasının Kuran’dan ve Sünnetten kaynaklanmadığına değindikten sonra, livata fiiline verilecek cezanın, bu fiilin topluma vereceği zararı örtmek ve yaygınlaşmasını önlemek amacı ile tazir cezası olabileceğini belirtir. (Kasani, VII/34; İbn Hümam, V/43vd.; İbn Âbidin, IV/29-30; Şirbini, IV/144.) İslâm Hukuku içinde yer alan üç tip ceza şeklinden biri olan tazir cezası; had ve kısas cezaları ile cezalandırılamayan, suç sayıldığı halde cezaları tespit edilmemiş olan, Allah'a veya kişiye karşı işlenen suçlarda verilen cezalara denir. (Yakut, 2011) </p>
                    <p>Eşcinselliğin Kuran’da açık bir şekilde ahlak dışı olarak nitelendirilmesine rağmen bu duruma bir ceza belirtilmemiş olması bu durumun suistimale açık olduğunu da gösterir. Örneğin İbn Hazm, topluma verilecek bir zarardan bahsetmektedir. Zararın tanımlanması da cezanın tanımlanması da problematiktir. Cezayı tanımlayacak kişinin bu noktadaki görüşleri cezanın boyutunu da etkileyecektir. Kaldı ki ceza verme eylemi bir zarar unsuruna bağlıysa, somut bir zarar eyleminin kanıtlanması da gerekecektir. Bu noktada Kuran’a yenilikçi bakışı benimseyen bazı Müslüman âlimler; adalet ve eşitlik gibi İslami değerlerle çatışan eşcinselliğe karşı yerleşik düşüncelerin gözden geçirilmesi için çabalamaktadır. (Weiss, 1998)</p>
                    <p>Peki, topluma verilecek zarardan ne kastedilmektedir? Bunu İslam’ın kabul ettiği geleneksel aile düzenine dayandırabiliriz. Şuara suresi 165-166. ayetlerde: “Rabbinizin sizler için yarattığı eşlerinizi bırakıp da insanlar arasından erkeklerle mi beraber oluyorsunuz?” buyrulmaktadır. Bu nedenle Kuran’da kadınların, erkekler için yaratıldığı ve bunun doğal olan durum olduğu vurgulanmaktadır. Bu doğal düzeni bozan her durum İslam’a aykırıdır diyebiliriz. İslam’a aykırı olduğundan, İslam’ın öngördüğü toplum düzenine de aykırı olmaktadır. </p>
                    <p>İslamiyet’in total bir yaşam tarzı olduğunu savunan Berktay (1995, 110) bireyin her davranışını İslam’ın kurallarına göre şekillendirmek zorunda olduğunu belirtmektedir. Bu total yaşam tarzı ise ona göre Müslüman ailenin İslami ahlak sınırları içinde yeniden yaratılmasına yol açar. Bizler aslında bu noktada ataerkilliğin ve heteronormativitenin dayatılmasına ve geleneksel aile kalıbının bu şekilde oluşması gerektiğine inandırılırız. Kadına ve erkeğe çizilmiş rollerin dışındaki herhangi bir davranış Allah’a karşı gelmek olarak yorumlanır. Yine Berktay (1995, 112) “Allah’ın ‘kelam’ı olan Kuran’a dayanarak belirtilen cinsiyet rolleri de değişmez ve dokunulmazdır; bu nedenle de bu konularda herhangi bir değişiklik önermek, tanrısal iradeyi bozma çabası, başka bir deyişle ‘küfür’ sayılır.” der. </p>
                    <p>Biz biliyoruz ki günümüzde bu kalıplar aşınmaktadır ve bu durum bazı dini otoriteleri tedirgin etmektedir. Kecia Ali’nin (2006, 94) de işaret ettiği gibi; cinsel davranışların yasal kontrolü risk altına girmektedir. Bu nedenle fıkıh âlimleri; meşru cinsel ilişki tanımının yeniden yorumlanmasına dair girişimlerin, kendi otoritelerini kemirmesinden korkmaktadır. Eşcinselliğe karşı tutumun sertliğinin altında yatan sebeplerden biri de budur. Dünyanın her yerinde hem kadın hem de LGBTI+ hareketinin yaygınlaşması ve “geleneksel aile” kavramının sorgulanması, dini tabuların yıkılmasına sebep olmaktadır. Peki dindar ve eşcinsel bireyin konumu nerede yer almaktadır? Eşcinsel bireylerin İslam’ı nasıl gördüklerini incelemek bu noktada önem arz etmektedir. Bu bireyler ikilemde midir yoksa dindarlık ve eşcinsellik arasında bir orta nokta bulunabilir mi?  </p>
                    <p>Eşcinsel ve dindar bireylerin yaşadığı ikilemi ele aldığımızda, bu sorunu çözmek adına bu bireylerin iki tür davranış biçimi geliştirdiğini söyleyebiliriz. (Kıraç, 2014) Birincisi; dindar ve eşcinsel birey, cinsel yönelimini reddetme eğiliminde olabilir bu sebeple de heteroseksüel bir yaşam tarzını seçer. İkinci davranış biçimi ise dinin eşcinsellik hakkındaki genel kabullerini reddetme ve dini inançta zayıflama şeklinde ortaya çıkar. Cinsel ya da dini kimlikleri daha güçlü ve katı olan bireyler bu ikilemi daha çok yaşamaktadır diyebiliriz. (Barret ve Barzan, 1996) Bu durum bireyde nasıl bir etki yaratmaktadır? Birey kendi özünün bütünsel bir parçasını; yani dini inancını veya cinsel kimliğini reddettiğinde, bu reddediş büyük olasılıkla bireyin akıl sağlığında derin ve negatif bir etki bırakmaktadır diyebiliriz. (Wagner, Serafini, Rabkin, Remien ve Williams, 1994) </p>
                    <p>Kıraç, “Dindar Eşcinsel Bireyin Manevi ve Cinsel Kimlik İkilemi” (2014) adlı çalışmasında şu soruyu sormuştur: “Türkiye’de yaşayan ve İslam dinine inanan eşcinsel birey, manevi durumu ile eşcinselliğe karşı inanç ya da tutumları arasında bir çelişki yaşamakta mıdır?”. Çalışması doğrultusunda, bireylerin eşcinsellikle ilgili düşüncelerine göre 4 farklı gruba ayrıldığı ve bu gruplaşmalarının temelinde cinsel yönelimlerini kabul edip edememe eğiliminin bulunduğu sonucuna ulaşmıştır. Bu bireylerin içinde cinsel yönelimlerini kabul eden grup daha az dindardır ve cinsel kimlik karmaşası yaşamayan bu grup yaşamlarını daha anlamlı bulmaktadır. Bu bize dinin eşcinselliğe karşı dışlayıcı tutumunun bireyler üzerindeki etkisini açıkça göstermektedir. Günümüzde, din ve eşcinsellik arasında bir orta nokta bulmaya çalışan, Kuran’ın farklı yorumlarını sunan hareketler belki de bu ikilemi bir gün yok edebilecektir. Bu tarz bir dışlamanın topluma hiçbir yararı yoktur ve bu dışlama açıkça toplumun bir kesiminin sürekli hedef gösterilmesine sebep olmaktadır. Hedef olarak gösterilen ve bir nefret siyasetine kurban edilen bu grup bazı şiddet eylemlerinin de odağı haline gelmektedir. Bu nedenle Çeçenistan’daki gey tecrit kamplarını incelemek istiyorum. </p>
                    
                    <h5>Çeçenistan’daki Gey Tecrit Kampları ve Homofobinin Görünür Eli</h5>
                    <p>Çeçenistan’daki gey tecrit kampları, gazeteci Elena Milashina tarafından Nisan 2017’de ortaya çıkarılmıştır. 1 Nisan’da Novaya gazetesi tarafından; yüzden fazla Çeçen erkeğin, başka erkeklerle cinsel ilişkide bulunmaları sebebiyle suçlandığı, bu kişilerin yerel yasalara dayanarak gözaltına alındıkları ve güvenlik otoritelerince gizli hapishanelere getirilerek burada elektroşok verilip, sopalarla dövüldükleri hatta bazılarının öldürüldükleri bildirilmiştir. (Brock ve Edenborg, 2020) </p>
                    <p>Çeçenistan devlet başkanı Ramazan Kadirov, HBO’ya verdiği röportajda gey tecrit kampları ile ilgili şu iddialarda bulunmuştu:</p>
                    <p>“Bu saçmalık. Bizim ülkemizde ‘öyle’ insanlar yok. Ülkemizde hiç gey yok. Var ise onları Kanada’ya götürebilirsiniz. Onları bizden uzağa götürün. Ülkemizde onlardan varsa, kanımızı temizlemek için onları götürün.” (Washington Post, 2017) </p>
                    <p>Eşcinsel bireylerin varlığını reddederek onları görünmez kılmaya çalışan Kadirov’un bir çelişki yarattığını söyleyebiliriz. Foucault’nun (1984) baskıyı tanımlayış biçimi bu noktada bize ışık tutacaktır: “Baskı hem yok olmaya mahkûm etme işlevi görür hem de bir susma emri, var olmayışın olumlanması ve dolayısıyla da tüm bu konularda söylenecek, görülecek ya da bilinecek hiçbir şey olmadığının tespit edilmesini sağlayacak biçimde işler.”  Yani Kadirov, bize aynı anda hem eşcinsellerin var olmadığını ve bu konuda konuşmanın bir anlamı olmadığını -söylemsel reddediş- hem de var olmamalarının ülke için daha yararlı olduğunu söylemektedir -bedensel reddediş-. Bir devletin; böyle bir inkarda bulunurken aynı zamanda şiddetli bir taciz, korkutma, işkence ve hatta varlığını reddettiği o insanları öldürme kampanyasını organize bir şekilde sürdürmesi, söylemsel ve bedensel yok etmenin karşılıklı bağlantılılığına işaret eder. (Taylor, 1997) Özetle, eşcinsellik yok sayılan ve yok sayıldığı halde yok edilmeye çalışılan bir duruma dönüşmüştür. </p>
                    <p>Şubat 2017’de bir erkeğin uyuşturucu kullandığı iddiasıyla gözaltına alınmasıyla beraber bu eşcinsel avının temeli atılmıştır. Telefon kayıtlarını inceleyen Çeçen polisler bu kişinin başka erkeklerle cinsel etkileşimde bulunduğunu ortaya çıkarmış ve böylece iletişim kurduğu erkekler de gözaltına alınmıştır. (Milashina ve Gordinenko, 2017) Ramazan Kadirov’un sağ kolu diyebileceğimiz, Çeçenistan’daki ikinci en güçlü adam olan Magomed Daudov’un bu temizleme hareketinde merkezi bir rol oynadığı ve hatta bazı tanıkların iddia ettiğine göre bizzat tecrit kamplarında bulunduğu bildirilmiştir. (Milashina,2017)</p>
                    <p>Çeçenistan’daki bu eşcinsel nefretini anlayabilmek için bu bölgedeki köktendinciliği ve toplumsal cinsiyete bakışı mercek altına almalıyız.  Eşcinsel karşıtlığının sadece bu sebeplerden kaynaklanmadığını kabul etmekle birlikte bu sebeplerin gey tecrit kamplarına giden süreçteki rolü göz ardı edilemez. Öncelikle İslam’ın rolünü ele alacağım. Çeçenistan çoğunluğu Müslüman olan bir ülkedir. Rusya ile girilen ayrılıkçı çatışmalar sonucunda Çeçenistan’da İslam’ın algılanışı yeniden tanımlanmıştır. (Scicchitano, 2019) Çatışmalar sonrasında İslam’ın daha geleneksel ve radikal bir yaklaşımı benimsenmiş ve geleneksel tanımlamaların dışındaki tüm İslami yorumlar reddedilmiştir. (Bedford ve Souleimanov, 2016) Bu noktada İslam toplumun her alanını kuşatmış, halk tarafından içselleştirilmiş ve sosyal hayata muhafazakâr bakış, toplumu günahtan “arındırma ya da temizleme” üzerine yoğunlaşmıştır. Çeçenistan’ın dini tarihine dair algısı; cumhuriyetin günahkârlardan arındırılması ve köktendinciliğin savunulması adına, namus cinayetlerinin ve devlet destekli temizleme hareketinin kullanılmasının önemli bir nedeni olmuştur. (Scicchitano, 2019) Sonuçta, dinin radikal bir yorumunun içselleştirilmesi toplumda belli standartların dışındaki tüm bireyleri zan altında bırakmıştır. Özellikle de dinin kalesi olan aile kurumuna en büyük “tehdit” olarak görülen LGBTIQ+ bireyler toplumda gittikçe daha çok göze batar hale gelmiştir. Toplumda namus cinayetlerinin normalleştirilmesi ve hatta haklı görülmesine kadar giden bu süreç bir kıyıma yol açmıştır. </p>
                    <p>Toplumsal cinsiyet rolleri konusuna gelecek olursak, bu noktada Çeçen erkeği ve kadının tarihsel olarak getirdiği algılayışlar bu toplumdaki eşcinsel bireylere bakışı etkilemektedir diyebiliriz. Şu soruyu sormak gerekir: Çeçen erkeği neyi ifade eder? Ne yapmalıdır ki geleneksel toplumun gidişatına ket vurmasın? Başka bir erkeği seven, destekleyen ve onunla cinsel ilişkide bulunan Çeçen gey ve biseksüel erkekler; “kadınsal bir kırılganlığı” bünyesinde barındırdığından ataerkil, maskülin ve askeri bir şekilde inşa edilmiş Çeçen ulus kimliğinin özünü tehdit etmektedir. (Scicchitano, 2019) Çeçen toplumunun ve günümüzdeki birçok toplumun erkekliğe verdikleri anlam, eşcinsel erkeklerin daha az erkek sayılmasına neden olmuş ve bunun sonucunda bu bireyler ayrımcılığa maruz kalmıştır. Erkekler “koruyan”, kadınlar ise “korunan” rollerine uydukları sürece toplumda kabul edilmekte aksi taktirde ise öldürülmeye kadar giden bir şiddetle karşı karşıya kalmaktadırlar. </p>
                    <p>Beden, toplumda tahakküm ilişkisinin merkezinde yer almaktadır. “Bourdieu’cü düşünüş, bedenin kendisini eril tahakküm uygulamalarının maddileşmiş yüzeyi sayar.” (Köse, 2016) Bu yüzdendir ki bedenin kontrolü iktidar mekanizmasının temel endişesidir. Eğer beden kontrol edilir, belli bir kalıba sokulur ve bedenin üstünde bir hegemonya kurulursa o zaman iktidar toplumda bir düzen üretebilir. Foucault’ya göre bedenin denetim altına alınması disipliner toplumun özüdür. (Foucault, 1992) Bu disipliner toplum kadına ve erkeğe farklı bedensel roller çizer. “Bourdieu’ye göre, eril beden üzerinden şekillenmiş olan eril imtiyazın temel tuzağı, erkeğin kendi içinde duyumsadığı kadınsı korkudan doğar…” (Köse,2016) Örneğin, eril bedenin güçsüzlüğe ya da herhangi bir “kadınsılığa” tahammülü yoktur. Bu nedenledir ki ataerkil ve askeri bir şekilde inşa edilmiş olan Çeçen ulus kimliği; içinde barındırdığı onlarca güç unsuruna rağmen, eşcinsel erkeklerin varlığını büyük bir tehdit olarak algılayacak kadar kırılgandır da. Çeçen erkeğinin idealize edilmiş biçimine uymayan bu kesimin tehdit ettiği asıl unsur beden üstünde hegemonya kurmaya çalışan iktidar mekanizmasıdır. Çünkü eşcinsel erkeğin varlığı standartlaşmış bedeni kalıplara uymamaktadır. Sonuç olarak, hem radikal dini bakışın eşcinselliğe olumsuz tavrı hem de toplumsal cinsiyete ve katı bir bedensel kontrol mekanizmasına sıkı sıkıya bağlılık bu bireyleri toplumda hedef haline getirmiş ve bu bireyler toplumda “temizlenmesi” gereken günahkârlar olarak algılanmıştır.</p>
                    <p>Gey tecrit kampından kurtulmayı başarabilen kişilerden biri olan Ruslan, yaşadıklarını BBC’den Sarah Rainsford ile yaptığı röportajda şu şekilde anlatmıştır: </p>
                    <p>“ …  Önceden insanları şantaj yapmak için sürekli tutukluyorlardı. Şu an gelinen nokta ise yok etme, gey insanları yok etme seviyesi. Böylece Çeçenistan’da hiç (gey) kalmayacak. Çeçenlerin gey olmaya hakkı yok. Onlar savaşçı, heteroseksüel veya sporcu olmalı. Gey olmak onlar için kabul edilebilir bir seçenek değil.  </p>
                    <p>… Kim gey olmak ister? Ama madem ki oldum, bu konuda ne yapabilirim? Gey olmamak için her şeyi yaptım. Evlendim. ‘Normal’ bir hayat yaşadım. Bundan kaçmak için her şeyi yaptım. Ama olmadı.</p>
                    <p>… Oraya (Çeçenistan) asla dönemem. Sadece güvenlik güçlerinden dolayı değil. Bizim zihniyetimize göre güvenlik güçleri benimle baş edemediyse bile kendi akrabalarım kesinlikle baş edecektir.”  (BBC, 2018)</p>
                    <p>Ruslan’ın ifadelerinden “toplumsal cinsiyetin” ülkede ne kadar dayatıldığını anlayabiliriz. Çeçen erkeği askerliği, sporculuğu ve heteroseksüel ilişkiyi kabul etmezse toplum da onu kabul etmeyecektir. Bunun nedeni bedensel kontrolü elinde tutmaya çalışan iktidar mekanizmasıdır. Kaldı ki bu erkeklerin “normal” hayatlar kurarak yaşamaya çalıştıklarını, evlendiklerini yani cinsel kimlik karmaşası yaşadıklarını da görüyoruz. Bu karmaşa içindeki yaşamın ağırlığı altında ezildikleri yetmezmiş gibi bir de devlet şiddetiyle karşı karşıya kalmışlardır. Kaçıp canlarını kurtardıklarında ise şu gerçekle yaşamak zorunda kalmaktadırlar: “Geri dönersem kendi kanımdan insanlar tarafından öldürülebilirim.” </p>

                    <h5>Sonuç</h5>
                    <p>Lût kavmi hikayesini temel alan tek tanrılı dinlerde eşcinsellik, bir günah ve doğal düzene karşı çıkış olarak görülmüştür. Tek tanrılı dinlerin eşcinselliği kimlik olarak değil cinsel davranış olarak ele aldığını söylemek yanlış değildir. Bu nedenle kimlik olarak eşcinsellik tanımlanmamış, cezai anlamda da yoruma bırakılmıştır. Bu noktada eşcinsel ve dindar bireyin yaşadığı ikilemin incelenmesi ve bu durumun bireylerin akıl sağlığına olumsuz etkide bulunacağını ifade etmek gerekmektedir. Çoğunluğu Müslüman olan Çeçen toplumunda, köktendinciliğin ve toplumsal cinsiyet rollerinin ülkedeki eşcinsellere karşı büyük bir şiddet ve temizleme kampanyasına sebep olduğunu söyleyebiliriz. Bu toplumda eşcinsel erkekler devlet eliyle şantaja, işkenceye uğramış ve öldürülmüşlerdir. Hayatlarını kurtarabilenler ise ülkelerine bir daha geri dönemeyeceklerinin bilincinde bir hayat sürmek zorunda kalmışlardır. Geri döndüklerinde namus cinayetine uğramaktan korkmaktadırlar. Devlet yetkilileri her ne kadar bu bireylerin ülkelerinde var olmadığını iddia etse de biz bu eşcinsel bireylerin varlığının da yaşadıkları şiddetin de farkındayız. Dışlayıcı dinsel söylemlerin ve radikal toplumsal cinsiyet rollerinin yarattığı bu şiddet ortamı kabul edilebilir bir durum değildir. Bu söylemlerin ve rollerin dayatılması toplumlarda ve şiddet mağduru bireylerde onarılması mümkün olmayan yaralar açmaktadır.</p>

                    <Referencecard2/>
                </div>
                
            </div>
        )
    }
}
